---
title: "Sevoflurane levels minute-by-minute analysis"
author: "Jerry Chao"
date: "April 20, 2021"
output: github_document
---

```{r setup, echo = FALSE}
library(tidyverse)
library(readxl)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
sevo_df = read_csv("./sevo_tidy.csv")

sevo_df_tidy =
  sevo_df %>% 
    pivot_longer(
      min_1:min_14,
      names_to = "minute",
      names_prefix = "min_",
      values_to = "sevo"
        ) %>% 
    mutate(
      min = as.double(minute)
    ) %>% 
    select(
      id, discont, min, sevo
    )

sevo_df_tidy %>%
  group_by(id, discont) %>% 
  ggplot(aes(x = min, y = sevo, color = id)) +
  geom_point(alpha = .6)

smooth_overall =
sevo_df_tidy %>%
  group_by(id, discont) %>% 
  ggplot(aes(x = min, y = sevo, color = id)) +
  geom_point(alpha = .6) +
  geom_smooth()

smooth_no_discont =
sevo_df_tidy %>%
  filter(
    discont == 0
  ) %>% 
  ggplot(aes(x = min, y = sevo, color = id)) +
  geom_point(alpha = .6) +
  geom_smooth()

smooth_discont =
sevo_df_tidy %>%
  filter(
    discont == 1
  ) %>% 
  ggplot(aes(x = min, y = sevo, color = id)) +
  geom_point(alpha = .6) +
  geom_smooth()

(smooth_no_discont + smooth_discont) / smooth_overall

sevo_df_tidy %>%
  ggplot(aes(x = min, y = sevo, color = id)) +
  geom_point(alpha = .6) +
  geom_line()

sevo_df_tidy %>%
  ggplot(aes(x = min, y = sevo, color = id)) +
  geom_boxplot()

sevo_df_tidy %>%
  ggplot(aes(group = discont, y = sevo)) +
  geom_boxplot()

sevo_df_tidy %>%
  ggplot(aes(group = discont, x = min, y = sevo)) +
  geom_violin()
```

